FROM golang:alpine AS build
ADD /src /app/
WORKDIR /app
RUN go build -o server .
FROM alpine
MAINTAINER mi ma <mimamo@momima.de>
COPY --from=build  /app/server /app/server
EXPOSE 80
CMD []
ENTRYPOINT ["/app/server"]



